[package]
authors = ["Michael R. Buche <dev@mrbuche.com>"]
categories = ["mathematics", "science"]
description = "c o n s p i r e"
edition = "2021"
keywords = ["conspire", "mrbuche"]
license = "GPL-3.0"
name = "conspire_wrapper"
version = "0.1.0"

[dependencies]
conspire = { features = ["constitutive"], git = "https://github.com/mrbuche/conspire.rs.git", rev = "b4de3f2109e86d733c5d3eeb0db548e3d14c5d25" }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
