[package]
authors = ["Michael R. Buche <dev@mrbuche.com>"]
categories = ["mathematics", "science"]
description = "c o n s p i r e"
edition = "2021"
keywords = ["conspire", "mrbuche"]
license = "GPL-3.0"
name = "conspire_wrapper"
version = "0.1.0"

[dependencies]
conspire = { features = ["constitutive"], git = "https://github.com/mrbuche/conspire.rs.git", rev = "f19dcf64890cb215134e4d610b753e05bb6bf27a" }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
