[package]
authors = ["Michael R. Buche <dev@mrbuche.com>"]
categories = ["mathematics", "science"]
description = "c o n s p i r e"
edition = "2024"
keywords = ["conspire", "mrbuche"]
license = "GPL-3.0"
name = "conspire_wrapper"
version = "0.1.0"

[dependencies]
conspire = { features = ["constitutive"], path = "../../conspire.rs" }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
