[package]
authors = ["Michael R. Buche <dev@mrbuche.com>"]
categories = ["mathematics", "science"]
description = "c o n s p i r e"
edition = "2024"
keywords = ["conspire", "mrbuche"]
license = "GPL-3.0"
name = "conspire_wrapper"
version = "0.1.0"

[dependencies]
conspire = { features = ["constitutive"], git = "https://github.com/mrbuche/conspire.rs.git", rev = "d0c00f309f59385a03b136d2712a6a20f263ad94" }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
