name: Pages
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}
on:
  pull_request:
    branches: main
  push:
    branches: main
  release:
    types: published
permissions: {}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
          view_top: 1
      - name: Toolchain
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: stable
      - name: Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      - name: Dependencies
        run: julia --color=yes -e 'using Pkg; Pkg.add(["DocStringExtensions", "Documenter"])'
      - name: Checkout (stable)
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.last_release.outputs.tag_name }}
          submodules: true
      - name: Stable
        run: |
          julia --color=yes -e 'using Pkg; Pkg.develop(path="."); Pkg.build("Conspire")'
          julia --color=yes docs/make.jl
          mkdir -p ../_site/stable/
          cp -r docs/build/* ../_site/stable/
      - name: Checkout (latest)
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Latest
        run: |
          julia --color=yes -e 'using Pkg; Pkg.develop(path="."); Pkg.build("Conspire")'
          julia --color=yes docs/make.jl
          mkdir -p ../_site/latest/
          cp -r docs/build/* ../_site/latest/
      - name: Site
        run: |
          cp docs/index.html ../_site/
          cp docs/favicon.ico ../_site/
          grep -rl "</title>" ../_site/ | xargs sed -i 's@</title>@</title><link rel="icon" type="image/x-icon" href="/Conspire.jl/favicon.ico">@'
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ../_site/
  Deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: Build
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
