name: Test
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}
env:
  CARGO_TERM_COLOR: always
on:
  pull_request:
    branches: [ main ]
permissions: {}
jobs:
  Julia:
    strategy:
      fail-fast: true
      matrix:
        julia-version: [1.10, 1.11]
        os: [macos-latest, ubuntu-latest]
        toolchain: [beta, nightly, stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Toolchain
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          components: clippy, rustfmt
          toolchain: ${{ matrix.toolchain }}
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --release -- -D warnings
      - name: Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - name: Test
        run: julia --color=yes -e 'using Pkg; Pkg.add(path="."); Pkg.test("Conspire")'
